name: Documentation Check

on:
  push:
    paths:
      - '**.md'
      - 'docs/**'
  pull_request:
    paths:
      - '**.md'
      - 'docs/**'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run markdown linter
      uses: DavidAnson/markdownlint-cli2-action@v13
      with:
        globs: |
          README.md
          CLAUDE.md
          docs/**/*.md
    
    - name: Check for broken links
      uses: lycheeverse/lychee-action@v1
      with:
        args: --verbose --no-progress './**/*.md'
        fail: false  # リンクチェックは警告のみ