name: Pull Request Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-info:
    name: PR Information
    runs-on: ubuntu-latest

    steps:
      - name: PR Details
        run: |
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "PR Author: ${{ github.event.pull_request.user.login }}"
          echo "Base Branch: ${{ github.event.pull_request.base.ref }}"
          echo "Head Branch: ${{ github.event.pull_request.head.ref }}"

  size-check:
    name: PR Size Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check PR size
        run: |
          CHANGED_FILES=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD | wc -l)
          ADDITIONS=$(git diff --numstat origin/${{ github.event.pull_request.base.ref }}...HEAD | awk '{s+=$1} END {print s}')
          DELETIONS=$(git diff --numstat origin/${{ github.event.pull_request.base.ref }}...HEAD | awk '{s+=$2} END {print s}')

          echo "Changed files: $CHANGED_FILES"
          echo "Additions: $ADDITIONS"
          echo "Deletions: $DELETIONS"

          if [ "$ADDITIONS" -gt 500 ]; then
            echo "⚠️ Large PR detected! Consider breaking it into smaller PRs."
          fi

  all-checks:
    name: All Checks Summary
    runs-on: ubuntu-latest
    needs: [pr-info, size-check]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          bun install
          cd apps/bun-demo && bun install

      - name: Run all checks
        run: |
          echo "🔍 Running Format Check..."
          bun run format:check || (echo "❌ Format check failed" && exit 1)

          echo "🔍 Running ESLint..."
          bun run lint || (echo "❌ ESLint check failed" && exit 1)

          echo "🔍 Running Type Check..."
          bun run typecheck || (echo "❌ Type check failed" && exit 1)

          echo "🔍 Running Bun Tests..."
          cd apps/bun-demo && bun test || (echo "❌ Bun tests failed" && exit 1)

          echo "✅ All checks passed!"

      - name: Comment PR
        uses: actions/github-script@v7
        if: success()
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ All CI checks passed! Ready for review.'
            })
        continue-on-error: true
